### ISSUE TITLE
Err messages I don't understand

### ISSUE THREAD

**Issue by bionaught** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#1]
REPL outputs "
>>> uftpd.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uftpd.py", line 413, in start
OSError: 23
>>>
"
Linux CLI outputs"
graham@graham-SonyVaio ~ $ ftp 192.168.0.25
ftp: connect: Connection timed out
ftp>"

I'd really like to be able to just edit Phyton files in Notepad ++ and just save over ftp using NppFTP (http://ashkulz.github.io/NppFTP/)

Hope someone else has managed to get this working on an ESP32 and can give me a pointer. I'm new to python and haven't got a clue what to do about these error messages.

**Comment by robert-hh** [comment]
uftpd.py runs on esp8266 only. it requires a special callback, which is not implemented in the ESP32 port. Besides that, I never got it working with NppFTP. You could use the ftp.py script, which works on ESP32, but does not work in background. 
You can use these whith some ftp clients like FileZilla and FireFTP. You can configer these to call an editor of your choice, like Npp, once you double-cklick on the file name.

**Comment by bionaught** [comment]
FireFTP did the trick. Files are opening in Notepad ++ now with syntax highlighting. I also have NppConsole plugin so entering the REPL and starting your ftp.py script is now making my learning curve much less steep.
Tis a bugger uftpd.py can't be used yet in the background on the ESP32.
Thanks for the quick ressponse.

**Comment by robert-hh** [comment]
From version='v1.9.3-575 of micropython on, the ESP32 branch too supports uftpd.py.
Edit: I tried the combination of the new firmware release, uftpd and NppFTP on Windows 10, and it worked.
