### ISSUE TITLE
Uploads not working on pyboard-D

### ISSUE THREAD

**Issue by kevinkk525** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#11]
I'm using uftp and can connect successfully, traverse directories and even download files but any uploads fail with the response "550 Fail". 
The filesystem still has space, micropython is version 1.15 nightly, pyboard is connected to the PC, webrepl is active but I don't even run any scripts.
Filezilla is set up for one connection, the same way ftp_thread.py works on my esp32, which I use regularly to push updates.

**Comment by robert-hh** [comment]
No problem here. Did you cd to the flash directory on pyboard? What happens if you deactivate webrepl.
If there is a collision with weprepl, can you try the foreground version ftp.py?

**Comment by kevinkk525** [comment]
Interesting. Yes I cd'ed into the flash directory where I have many files that were copied using windows. I can download all of them but I can't upload anywhere.
Disabling webrepl didn't change anything. Running the foreground version of ftp_thread works just fine (since there is no _thread module it runs as a foreground application). ftp_thread prints all commands while uftp stays silent (but that's by design iirc).

The simplest test script I used is this:
```
import time
import network

st = network.WLAN(network.STA_IF)
st.active(True)
st.connect("ssid", "pw")
c = 0
while not st.isconnected():
    print(".", end="")
    time.sleep(1)
    c += 1
    if c > 5:
        st.connect("ssid", "pw")
        print("+", end="")
        c = 0

import pysmartnode.libraries.ftpserver.uftpd
```

(I made sure I'm using the latest version of the ftp_server)

**Comment by robert-hh** [comment]
That's indeed strange. Could you try using the command line version of ftp on the PC. There you get more interim messages. It works on Windows too.
Edit: Is the file name of the to-be-uploaded file special in any way, or one of the files already stored on the board?

**Comment by kevinkk525** [comment]
Ok I tried with ubuntu lftp and it worked, so I found the problem afterwards: With the uftp version I need to use the "passive" transfer mode in filezilla, while ftp_thread works fine with the "active" mode of file transfer.

After changing that, I was able to upload any file ( all of the tested files were already on the board and worked with ftp_thread).

Did you use active or passive mode?

**Comment by robert-hh** [comment]
The actual version of uftpd.py supports active mode as well.

**Comment by kevinkk525** [comment]
Hmm that is strange. Just to be sure I removed uftpd.py from the device and copied it again from your repository. Also did machine.reset() but the result is the same: the passive mode works, the active mode doesn't.

So I added some exception printing and this is what I got:
```
FTP Command connection from: 192.168.178.29
Command=USER, Payload=anonymous
Command=CWD, Payload=/flash
Command=TYPE, Payload=I
Command=PORT, Payload=192,168,178,29,217,185
Command=STOR, Payload=config.mpy
Traceback (most recent call last):
  File "./pysmartnode/libraries/ftpserver/uftpd.py", line 292, in exec_ftp_command
  File "./pysmartnode/libraries/ftpserver/uftpd.py", line 170, in open_dataclient
OSError: 1030188649
```

But what I don't understand is that all commands in active mode work the same way and open a connection to the ftp client in data_client.connect(), so why does STORJ fail but LIST and RETR work just fine?

(additionally an exception is thrown in line https://github.com/robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD/blob/32740db4d6ec70db14f8aea3f81943bfe85158e9/uftpd.py#L302 because data_client isn't defined when it runs into the exception but that's not the main problem here)

Using passive mode is an acceptable mode but if active mode should work, then I can't find the error.

**Comment by robert-hh** [comment]
Could you try running the board in STA mode? I always do so, and that is a difference I see.

**Comment by kevinkk525** [comment]
```
st = network.WLAN(network.STA_IF)
st.active(True)
st.connect("ssid", "pw")
```

Isn't that STA mode?


Just to be thorough I just tested uftpd on my esp32 with active mode and it worked just fine, so somehow this is a pyboard-D specific problem.
