### ISSUE TITLE
timeout if no one connects

### ISSUE THREAD

**Issue by elministerr** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#13]
Hi,

ftp.py are pretty useful for me. I just want "import ftp" a few seconds in my script and if no one connect it breaks and go on further.. 

is it possible somewhere in code to define a timeout ? 

thanks

regards

**Comment by robert-hh** [comment]
That should be possible. In line 128, ftpsocket timeout is set to None. In line 152 ftpsocket waits for a connection. If a timeout is set, that call will give a timeout error on expiry, which will end the program. To make that ending gracefully, you have to add an except clause before line 324, so the end of the code should then look like:

```
     except Exception as e: 
        print(e) 
     finally:
        datasocket.close()
        ftpsocket.close()
        if dataclient is not None:
            dataclient.close()
```
You could also make the timeout optional by making it an argument to the function ftpserver() with None as default value.

**Comment by robert-hh** [comment]
I have updated the repository with the changes I mentioned.

**Comment by elministerr** [comment]
oh you are nice. Thank you.. i have already use it and it works like a charm! Thanks!

**Comment by robert-hh** [comment]
You're welcome.
