### ISSUE TITLE
README.md expanded

### ISSUE THREAD

**Issue by DG12** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#15]
Before I create a pull request.
Please review my expanded version of the README.md

1. Rather than ftpd is too big, ESP8266 has size restrictions :-)
2. listed commands implemented and those not
3. add using
4. rearranged and renamed some sections

https://github.com/DG12/FTP-Server-for-ESP8266-ESP32-and-PYBD/tree/expand-README.md#readme

And provide me with any feedback.

**Comment by robert-hh** [comment]
That looks ok. While you are working on it, please remove and mentioning for fireftp. That extension is not supported any more by Firefox.
