### ISSUE TITLE
Pycom ftp

### ISSUE THREAD

**Issue by DG12** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#17]
Do you happen to know where the source for the FTP
 server used in pycom?

**Comment by robert-hh** [comment]
For Pycom it is here: https://github.com/pycom/pycom-micropython-sigfox/tree/Dev_release_v1.20/esp32/ftp

For MicroPython, there is a ftp server in the cc3200 Port: https://github.com/robert-hh/micropython/tree/w60x/ports/cc3200/ftp

There is also branch for the Winner W60x chip supported by me which also has a ftp server, where the implementation is a little bit simpler: https://github.com/robert-hh/micropython/blob/w60x/ports/w60x/tools/ftpserver.c

**Comment by DG12** [comment]
Thanks. Some how the only portion of that repo I didn’t look at was  sigfox

**Comment by DG12** [comment]
Line 217 explains it:
         { "May" }, { "Jun" }, { "Jul" }, { "Ago" },
Should be Aug

I guess I’ll post a pull reassert.
Thanks again

**Comment by robert-hh** [comment]
Pycom does not maintain these products any more. You can make a PR, but most likely it will ne ignored.
