### ISSUE TITLE
uftpd does not 'assume QUIT' when client disconnected from AP.

### ISSUE THREAD

**Issue by puppet13th** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#19]
example code:
```py
import network
from time import sleep_ms
from machine import reset, WDT
import uftpd

ap = network.WLAN( network.AP_IF )
ap.config( authmode=4 ,password='12345678' )
ap.active(True)

uftpd.start(port=2121,verbose=1,splash=True)
wdt = WDT(timeout=120_000)
while True:
    sleep_ms( 60_000 )
    if uftpd.client_list:
        print('')
        print('wdt feed', uftpd.client_list )
        print('')
        wdt.feed()
    else:
        print('')
        print('no client connected!', uftpd.client_list )
        print('')
```

when client still connected to AP but on idle connection, uftpd will 'assume QUIT' after session time out.
```
FTP Data connection with: 192.168.4.2

wdt feed [<FTP_client object at 3ffe5930>]

*** No data, assume QUIT

no client connected! []
```

if client disconnected from AP before session timeout, uftpd did not 'assume QUIT':
```
FTP Data connection with: 192.168.4.2

wdt feed [<FTP_client object at 3ffe5ed0>]

wdt feed [<FTP_client object at 3ffe5ed0>]

wdt feed [<FTP_client object at 3ffe5ed0>]
```

tried using:
```
MicroPython v1.19.1-608-gb52fe52d3 on 2022-11-03; ESP32 module with ESP32
Type "help()" for more information.
```

**Comment by robert-hh** [comment]
So I try the same:
- Connect to an AP in station mode.
- Start uftpd and set uftpd.verbose_l = 2
- Connect to the esp32 from another terminal
- Close the WiFi connection with wlan.active(False)

At that point UFTPD reports an error, but continues to run:
```
>>> Exception in exec_ftp_command:
Traceback (most recent call last):
  File "ftpd.py", line 191, in exec_ftp_command
OSError: [Errno 113] ECONNABORTED
```
Line 191 is at trying to get another command.
I can change the code to handle that situation as quit.

**Comment by puppet13th** [comment]
> So I try the same:
> 
> * Connect to an AP in station mode.
> * Start uftpd and set uftpd.verbose_l = 2
> * Connect to the esp32 from another terminal
> * Close the WiFi connection with wlan.active(False)
> 
> At that point UFTPD reports an error, but continues to run:
> 
> ```
> >>> Exception in exec_ftp_command:
> Traceback (most recent call last):
>   File "ftpd.py", line 191, in exec_ftp_command
> OSError: [Errno 113] ECONNABORTED
> ```
> 
> Line 191 is at trying to get another command. I can change the code to handle that situation as quit.

thank you for your reply

in your case, ESP32 running uftpd disconnected from AP.
in my case the client(android phone) that using ESP32 uftpd service that disconnected from AP. that's why there is no error occurred in my test.
