### ISSUE TITLE
support ethernet interface

### ISSUE THREAD

**Issue by phatpaul** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#2]
Seems it doesn't support the Ethernet interface.

Here's how I start the Ethernet network on my Olimex ESP32-EVB.

>>> import network
>>> import machine
>>> eth_if = network.LAN(mdc = machine.Pin(23), mdio = machine.Pin(18), power = machine.Pin(17), phy_type = network.PHY_LAN8720, phy_addr=0)
>>> eth_if.active(1)
>>> eth_if.ifconfig()
('192.168.33.153', '255.255.255.0', '192.168.33.1', '192.168.33.1')

Then start uftpd with:
>>> import uftpd

I'm able to connect to the server now, but unable to list dir or transfer.  Using Filezilla on Win7.  Set mode passive, max connections=1.  

I see the part of the code that is tied to using the WLAN interface 
https://github.com/robert-hh/FTP-Server-for-ESP8266-and-ESP32/blob/be5b27a47d71c4b93fdcc302bfce9b045515d622/uftpd.py#L428

and 
https://github.com/robert-hh/FTP-Server-for-ESP8266-and-ESP32/blob/be5b27a47d71c4b93fdcc302bfce9b045515d622/ftp.py#L124

I'll try hacking it to work with LAN now, but I'm new at python, so I'd appreciate a proper fix.

**Comment by robert-hh** [comment]
I had tested a version with the WIznet5k interface on pyboard. I made the initial section of ftp.py look like;
```
    if True:
        WIZNET5K_nic = network.WIZNET5K(pyb.SPI(1), pyb.Pin.board.X5, pyb.Pin.board.X4)
        WIZNET5K_nic.active(1)
        WIZNET5K_nic.ifconfig(('10.0.0.139', '255.255.255.0','10.0.0.240', '10.0.0.240'))
    else:
        WIZNET5K_nic = network.WIZNET5K()

    DATA_PORT = 13333

    ftpsocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    datasocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    ftpsocket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    datasocket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    ftpsocket.bind(socket.getaddrinfo("0.0.0.0", 21)[0][4])
    datasocket.bind(socket.getaddrinfo("0.0.0.0", DATA_PORT)[0][4])

    ftpsocket.listen(1)
    ftpsocket.settimeout(None)
    datasocket.listen(1)
    datasocket.settimeout(None)

    msg_250_OK = '250 OK\r\n'
    msg_550_fail = '550 Failed\r\n'
    addr = WIZNET5K_nic.ifconfig()[0]
```
The data needed is addr, the own IP address, which comes from ifconfig().  For testing, you can set it to the known IP address, like:
    addr = '192.168.33.153'
or
    addr = eth_if.ifconfig()[0]

I also tested the simple ftp server using threading, which works quite well, dropping the need to use that special callback, which is also used by webrepl.

**Comment by phatpaul** [comment]
That was easy.  https://github.com/phatpaul/FTP-Server-for-ESP8266-and-ESP32/commit/886db62eaddf0d6c392d32d27f50fcc87c590436


BTW, Looks like it was already working for me in active mode.  (I had followed some advice to set Filezilla to passive mode)

another BTW:  I don't think the method for choosing the IP for passive mode will work if the client is on another subnet (i.e. routed).  It is masking the client's IP with it's netmask (to get the subnet) and comparing that with the server's subnet.  But the subnets don't necessarily have to be the same.
A better way is to choose the IP based on which interface the request is coming in on.  But how can we tell what interface the request originated on if multiple interfaces are active?

**Comment by robert-hh** [comment]
Yes, one of the recent changes to ftp.py was the support of the active mode, allowing to use Windows command line ftp.
And yes, I had the same question to tell the interface of the request. And so I assumed at least that the devices are on the same subnet. For the initial purpose, local file transfer to the ESP8266, that was good enough.

**Comment by robert-hh** [comment]
I uploaded the threading variant of ftp.py, which you might adapt & test. I do dnot fully test it yet. I tried just a few clients on Linux and Windows. Using threading, also the uftpd variant could be enhanced into supporting multiple sessions. But for me that seems to be overkill.
