### ISSUE TITLE
Username and password ?

### ISSUE THREAD

**Issue by wilson405** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#20]
I need to implement a username and password, please how do I do it?

**Comment by robert-hh** [comment]
Look at uftpd.py, line 222 ctd. There are comments telling about user name and password check, and what the code has to return. At these statements, user name and password are in the `payload` variable. It is up to you how you want to manage the user names and passwords, either static as part of the code or dynamic.

**Comment by monit-org** [comment]
Hi, I tried this solution, although it gives user name in payload, but password does not show up in any case? is there a way to check password too?

**Comment by robert-hh** [comment]
Did you return `cl.sendall("331 Need password.\r\n")` at the user command?
Then, the password will be requested.
