### ISSUE TITLE
Transfer files named with Chinese characters

### ISSUE THREAD

**Issue by jokerElsa** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#21]
Everyting works great!

but when I try to send file named with Chinese characters the server log shows as follow:

```
FTP Data connection with: 
Command=NOOP, Payload=
Command=CWD, Payload=/
Command=TYPE, Payload=I
Command=PASV, Payload=
Exception in exec_ftp_command: 
---[Errno 104] ECONNRESET(I print this line myself)
*** No data, assume QUIT
```

just use Windows file explorer as client and the progress bar stuck for a long time and then saids timeout
and then the server is also cannot be accessed
(for now I call restart after `log_msg(1, "*** No data, assume QUIT")` to continue use the server

At first i guess it is the encoding is not right so I tried "gbk, gb2312" at around line 193 still not working

I'm pretty new in both mpy and ftp sorry to open an issue for this and thanks for the time.

**Comment by robert-hh** [comment]
Sorry for the confusion. As far as I know, MicroPython only supports UTF-8 encoding. So at the moment you can only try to use Latin characters for file names.

**Comment by jokerElsa** [comment]
> Sorry for the confusion. As far as I know, MicroPython only supports UTF-8 encoding. So at the moment you can only try to use Latin characters for file names.

thank for the reply and time
