### ISSUE TITLE
Could not start transfer error

### ISSUE THREAD

**Issue by dukeduck1984** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#3]
Hi Robert,

The uftpd has worked well with my esp32 until today.  FileZilla failed to upload the files, no matter how I tried (restart the esp32, plug and unplug the usb cable etc.).  The error message showed in the FileZilla console as below.

```
Response:	150 Opened data connection.
Response:	550 Fail
Error:	File transfer failed
```

I can see the file being created but the file size is 0 bytes.

The firmware version:
MicroPython v1.11-182-g7c15e50eb on 2019-07-30; ESP32 module with ESP32

What could be wrong?  The file system corrupted?

Thanks,
Kaiyuan

**Comment by robert-hh** [comment]
You must set Filezilla to use only one session for file transfers.

**Comment by dukeduck1984** [comment]
I did set the maximum number of connections to 1, if that's what you meant?

**Comment by dukeduck1984** [comment]
It's weird that if a file failed to upload (0 bytes or just partially uploaded) once, this file will never be uploaded correctly again, even if I delete it from the esp32.  I will have to erase and reflash the board to  do it all over again.

**Comment by robert-hh** [comment]
Yes. You may have to redo that for every server you configure. Is there still space available on the flash file system? And do you use valid files names?
> It's weird that if a file failed to upload (0 bytes or just partially uploaded) once, this file will never be uploaded correctly again, even if I delete it from the esp32. I will have to erase and reflash the board to do it all over again.

I never had that. I only had to remove it from the device. Are you by chance using webrepl at the same time? That's not possible.

**Comment by robert-hh** [comment]
What is the size of the file you try to upload?

**Comment by robert-hh** [comment]
Besides that, this issue should be raised at the repository of uftpd.(https://github.com/robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD), since it is not related to the micropython firmware.

**Comment by dukeduck1984** [comment]
```
>>> uos.statvfs('/')
(4096, 4096, 506, 0, 0, 0, 0, 0, 0, 255)
```
Does it mean there's no more space on the flash?

The largest single file is less than 400kb.

**Comment by robert-hh** [comment]
That's what it means. The total size is about 2 MByte. But many small files can consume more space than expected, since even a one byte file allocates at least one sector (4k).

**Comment by dukeduck1984** [comment]
Indeed it's because there's no more space on the flash...  I deleted a few files and the uploading worked again.  I will have to move the frontend files to the sd card...

Thanks for the help Robert.  I will close this issue.
