### ISSUE TITLE
Automatically send file when connected

### ISSUE THREAD

**Issue by asturkoglu** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#4]
Is there any way to send a file automatically when ftp connection is established? When I started ftp via import ftp command, I want to send a specific file then stop the connection everytime. I don't want to control download/upload mechanism from computer. ESP32 should handle it by itself. 
I'm recording sound with my ESP32 for 3s. After the record finished, I'm looking for a way to send it to my computer automatically.

**Comment by robert-hh** [comment]
This repo is a server, not the client. The server responds to requests from clients, which asks for an action. You need a ftp client. A suitable one is here: 	https://github.com/SpotlightKid/micropython-ftplib.git
I made a short test, and it works. You have to set up a ftp server as the counterpart on your computer.

**Comment by asturkoglu** [comment]
Thank you for the information. Now I'm working with your code on ESP32, works well. Previously, I had worked with .ino FTP server, but sometimes ESP was crashing during connection . This is much more stable. 
For now, I'm opening an connection after record for a determined time, then closing it. During this time my python code (on computer) retrieving the file.
However, I'll try your recommendation later.
Best regards,
