### ISSUE TITLE
Compiling not truly necessary

### ISSUE THREAD

**Issue by jdtsmith** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#6]
I've included `uftpd.py` under `lib/` and imported and run it without problems on an ESP32.  The warning on the README might scare people away who could use it without rolling their own firmware with frozen in byte code!

**Comment by robert-hh** [comment]
Thanks for the comment. As far as I remember, that results from the first ESP8266 only version of the code, which left very little space in RAM.

**Comment by robert-hh** [comment]
I have updated the othtr variants too and modified the comment in README.
