### ISSUE TITLE
out of memory on ESP8266

### ISSUE THREAD

**Issue by bachi76** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#7]
Unfortunately I get a mem error on the ESP8266. Added uftp.py + a simple main.py with only 
 `import uftpd` in it. Result:

> MemoryError: memory allocation failed, allocating 1674 bytes
> MicroPython v1.13 on 2020-09-11; ESP module with ESP8266

**Comment by robert-hh** [comment]
As detailed in the README file, the heap space of the esp8266 is to small for a regular import. You have either to import it as precompiled file or include it into the flash as frozen bytecode, as has been written in the README file:

**Comment by bachi76** [comment]
Ahh.. I stand corrected. I actually looked for memory info in the readme, but overlooked the intro it seems :).
