### ISSUE TITLE
can just run as a ftp client

### ISSUE THREAD

**Issue by m986883511** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#9]
I test your project, ftp server is work on esp32, thank you very much.

and I see your code have FTP_client, can just start a ftp client? no ftp server.

**Comment by robert-hh** [comment]
Thank you very much. 
About your question. There is no ftp client in the repository, just different variants of the ftp server. The file uftpd.py starts a ftp server in background. It works on esp8266 and esp32 with the micropython.org firmware. It requires a specific socket command. The file ftp.py contains a ftp server which runs in foreground and uses standard socket commands only. You would start it from the REPL, close the terminal window and then run the ftp client from you PC. There are also ftp_pycom.py and ftp_thread.py, which also implement a ftp server. ftp_pycom.py is for pycom devices, and only useful in combination with the Windows command line ftp client. ftp_thread uses threading for background operation.
Besides that, I tested a ftplib.py on MicroPython devices for operation as a client, and it works well. See: 	https://github.com/SpotlightKid/micropython-ftplib.git

**Comment by m986883511** [comment]
> Thank you very much.
> About your question. There is no ftp client in the repository, just different variants of the ftp server. The file uftpd.py starts a ftp server in background. It works on esp8266 and esp32 with the micropython.org firmware. It requires a specific socket command. The file ftp.py contains a ftp server which runs in foreground and uses standard socket commands only. You would start it from the REPL, close the terminal window and then run the ftp client from you PC. There are also ftp_pycom.py and ftp_thread.py, which also implement a ftp server. ftp_pycom.py is for pycom devices, and only useful in combination with the Windows command line ftp client. ftp_thread uses threading for background operation.
> Besides that, I tested a ftplib.py on MicroPython devices for operation as a client, and it works well. See: https://github.com/SpotlightKid/micropython-ftplib.git

thank you for your replay
